version: '3.8'

services:
  # Simple PostgreSQL for development
  postgres:
    image: postgres:15-alpine
    container_name: truecrime-postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: truecrime
      POSTGRES_PASSWORD: truecrime
      POSTGRES_DB: truecrime_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U truecrime -d truecrime_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: truecrime-redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_dev_data:
    name: truecrime-postgres-dev-data
  redis_dev_data:
    name: truecrime-redis-dev-data